## TRACK SELECTION
slang=en,eng,English

## PLAYBACK CONTROL
shuffle=yes
hr-seek=yes
hr-seek-framedrop=no
loop-playlist=inf
stop-playback-on-init-failure=yes

## PROGRAM BEHAVIOR
reset-on-next-file=brightness,contrast,gamma,saturation,hue,target-peak,target-contrast,gamut-mapping-mode,tone-mapping,tone-mapping-param,inverse-tone-mapping,hdr-compute-peak,vf
load-auto-profiles=yes

## WATCH LATER
save-position-on-quit=yes

## VIDEO
vo=gpu-next
hwdec=nvdec
hwdec-extra-frames=12
hwdec-codecs=all
deinterlace=yes
video-output-levels=full
vd-lavc-film-grain=gpu
vd-lavc-dr=yes

## AUDIO
audio-file-auto=fuzzy
audio-normalize-downmix=yes
volume=50

## SUBTITLES
sub-auto=exact
sub-ass-override=no
sub-fix-timing=yes
blend-subtitles=yes
demuxer-mkv-subtitle-preroll=yes
sub-font-size=55
sub-color="#FFFFFF"
sub-border-size=1.2
sub-outline-color="#000000"
sub-back-color="#000000"
sub-shadow-offset=0.85
sub-blur=0.0

## WINDOW
keep-open-pause=no
border=no
fullscreen=yes
snap-window=yes
cursor-autohide=100
force-window=yes
idle=no

## EQUALIZER
saturation=50

## DEMUXER
demuxer-max-bytes=400M
demuxer-max-back-bytes=200M
directory-mode=recursive
force-seekable=yes

## OSD
osd-duration=2000
osd-font-size=28
osd-color="#FFFFFF"
osd-border-color="#000000"
osd-border-size=2
osd-shadow-color="#000000"
osd-shadow-offset=1
osd-align-x=center
osd-margin-y=40
osd-level=1

## SCREENSHOT
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-directory="~/Downloads"
screenshot-png-compression=7

## CACHE
cache=yes
cache-secs=20

## GPU RENDERER OPTIONS
scale=ewa_lanczos4sharpest
cscale=spline36
dscale=mitchell
tscale=oversample
tscale-blur=0.7
tscale-clamp=0.1
tscale-taper=0.1
tscale-radius=2.0
scale-antiring=0.2
cscale-antiring=0.2
dscale-antiring=0.2
tscale-antiring=0.1
tscale-window=blackman
correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes
interpolation=yes
dither-depth=16
dither-size-fruit=8
dither=fruit
temporal-dither=yes
temporal-dither-period=4
vulkan-swap-mode=fifo
vulkan-async-compute=yes
#glsl-shader="~~/shaders/NVScaler.glsl"
#glsl-shader="~~/shaders/NVSharpen.glsl"
glsl-shader="~~/shaders/CAS.glsl"
#glsl-shader="~~/shaders/FSR.glsl"
deband=yes
deband-iterations=4
deband-threshold=50
deband-range=16
deband-grain=6
gpu-context=x11vk
gpu-api=vulkan
target-colorspace-hint=yes
target-colorspace-hint-mode=target
target-prim=bt.709
target-trc=gamma2.2
target-peak=250
target-contrast=1600
target-gamut=bt.709
sdr-adjust-gamma=yes
treat-srgb-as-power22=input
tone-mapping=bt.2446a
inverse-tone-mapping=yes
gamut-mapping-mode=absolute
hdr-compute-peak=yes
hdr-peak-percentile=99.95
hdr-contrast-recovery=0.98

## VIDEO SYNC
video-sync=display-resample
video-sync-max-video-change=3

## AUTO-PROFILES
[extension.mkv]
profile-restore=copy
deinterlace=no